### ISSUE TITLE
I can not find annotation_FSC147_384.json and ImageClasses_FSC147.txt 

### ISSUE THREAD

**Issue by cc19860606** [flyinglynx/Bilinear-Matching-Network#4]
Please follow the [FSC-147 official repository]to download and unzip the dataset. However, it is a 404 page...
I download the database form https://github.com/cvlab-stonybrook/LearningToCountEverything". There are only Images and gt_density_maps.

**Comment by flyinglynx** [comment]
Hi, the detailed annotation and data split files are provided in FamNet official implementation repository https://github.com/cvlab-stonybrook/LearningToCountEverything/tree/master/data. Thanks! We will update the readme file.
