### ISSUE TITLE
3.5. Implementation Details：Network Architecture.

### ISSUE THREAD

**Issue by ONEISALL-h** [flyinglynx/Bilinear-Matching-Network#7]
I conducted the test and your work has achieved good results. I have some questions to ask.
As described in the article _The feature backbone consists of the first 4 blocks of ResNet-50 [12], which outputs the feature maps of 1024 channels._ Why use the ResNet-50 backbone instead of another deeper network? Is there any specific reason to use ResNet-50? 
Thank you!

**Comment by flyinglynx** [comment]
Hi. In this work we use ResNet-50 for fair comparisons with previous works [CFOCNet](https://ieeexplore.ieee.org/document/9423155) and [FamNet](https://github.com/cvlab-stonybrook/LearningToCountEverything). 

I have not tested other deeper backbones. Sorry that I really have no idea how backbones like swin and convnext will perform. I tested ResNet-18 and the MAE on validation set increases to around 18. I notice a recent work [(link)](https://arxiv.org/abs/2201.08959) obtains better performance but using only ResNet-18, unfortunately the code is not released.

Whether better backbone can improve performances on counting tasks is doubtful. According to my experimence on class-specific counting tasks, simple VGG backbone may performs better than ResNet. Maybe you can test other backbones and see the impact of backbones on class-agnostic counting.
